// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Questioner API",
    "version": "0.1"
  },
  "host": "localhost:8080",
  "paths": {
    "/api/task/{id}": {
      "get": {
        "parameters": [
          {
            "type": "integer",
            "format": "uint64",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Task to be worked on",
            "schema": {
              "$ref": "#/definitions/Task"
            }
          }
        }
      }
    },
    "/api/task/{id}/resolve": {
      "get": {
        "parameters": [
          {
            "type": "integer",
            "format": "uint64",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Correct answers",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Answer"
              }
            }
          }
        }
      }
    },
    "/api/task/{id}/solve": {
      "get": {
        "parameters": [
          {
            "type": "integer",
            "format": "uint64",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "format": "uint64",
            "name": "solutionID",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Check if solution is correct",
            "schema": {
              "type": "boolean"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Answer": {
      "properties": {
        "id": {
          "type": "integer",
          "format": "uint64"
        },
        "text": {
          "type": "string"
        }
      }
    },
    "Task": {
      "properties": {
        "answers": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Answer"
          }
        },
        "id": {
          "type": "integer",
          "format": "uint64"
        },
        "question": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Questioner API",
    "version": "0.1"
  },
  "host": "localhost:8080",
  "paths": {
    "/api/task/{id}": {
      "get": {
        "parameters": [
          {
            "type": "integer",
            "format": "uint64",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Task to be worked on",
            "schema": {
              "$ref": "#/definitions/Task"
            }
          }
        }
      }
    },
    "/api/task/{id}/resolve": {
      "get": {
        "parameters": [
          {
            "type": "integer",
            "format": "uint64",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Correct answers",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Answer"
              }
            }
          }
        }
      }
    },
    "/api/task/{id}/solve": {
      "get": {
        "parameters": [
          {
            "type": "integer",
            "format": "uint64",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "format": "uint64",
            "name": "solutionID",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Check if solution is correct",
            "schema": {
              "type": "boolean"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Answer": {
      "properties": {
        "id": {
          "type": "integer",
          "format": "uint64"
        },
        "text": {
          "type": "string"
        }
      }
    },
    "Task": {
      "properties": {
        "answers": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Answer"
          }
        },
        "id": {
          "type": "integer",
          "format": "uint64"
        },
        "question": {
          "type": "string"
        }
      }
    }
  }
}`))
}
