// Code generated by ogen, DO NOT EDIT.

package restapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// APITaskIDGet implements GET /api/task/{id} operation.
//
// GET /api/task/{id}
func (UnimplementedHandler) APITaskIDGet(ctx context.Context, params APITaskIDGetParams) (r *Task, _ error) {
	return r, ht.ErrNotImplemented
}

// APITaskIDResolveGet implements GET /api/task/{id}/resolve operation.
//
// GET /api/task/{id}/resolve
func (UnimplementedHandler) APITaskIDResolveGet(ctx context.Context, params APITaskIDResolveGetParams) (r []Answer, _ error) {
	return r, ht.ErrNotImplemented
}

// APITaskIDSolveGet implements GET /api/task/{id}/solve operation.
//
// GET /api/task/{id}/solve
func (UnimplementedHandler) APITaskIDSolveGet(ctx context.Context, params APITaskIDSolveGetParams) (r bool, _ error) {
	return r, ht.ErrNotImplemented
}
