// Code generated by ogen, DO NOT EDIT.

package restapi

// OperationName is the ogen operation name
type OperationName = string

const (
	APITaskIDGetOperation        OperationName = "APITaskIDGet"
	APITaskIDResolveGetOperation OperationName = "APITaskIDResolveGet"
	APITaskIDSolveGetOperation   OperationName = "APITaskIDSolveGet"
)
