// Code generated by ogen, DO NOT EDIT.

package restapi

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// APITaskIDGet implements GET /api/task/{id} operation.
	//
	// GET /api/task/{id}
	APITaskIDGet(ctx context.Context, params APITaskIDGetParams) (*Task, error)
	// APITaskIDResolveGet implements GET /api/task/{id}/resolve operation.
	//
	// GET /api/task/{id}/resolve
	APITaskIDResolveGet(ctx context.Context, params APITaskIDResolveGetParams) ([]Answer, error)
	// APITaskIDSolveGet implements GET /api/task/{id}/solve operation.
	//
	// GET /api/task/{id}/solve
	APITaskIDSolveGet(ctx context.Context, params APITaskIDSolveGetParams) (bool, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
