// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetAPITaskIDSolveHandlerFunc turns a function with the right signature into a get API task ID solve handler
type GetAPITaskIDSolveHandlerFunc func(GetAPITaskIDSolveParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAPITaskIDSolveHandlerFunc) Handle(params GetAPITaskIDSolveParams) middleware.Responder {
	return fn(params)
}

// GetAPITaskIDSolveHandler interface for that can handle valid get API task ID solve params
type GetAPITaskIDSolveHandler interface {
	Handle(GetAPITaskIDSolveParams) middleware.Responder
}

// NewGetAPITaskIDSolve creates a new http.Handler for the get API task ID solve operation
func NewGetAPITaskIDSolve(ctx *middleware.Context, handler GetAPITaskIDSolveHandler) *GetAPITaskIDSolve {
	return &GetAPITaskIDSolve{Context: ctx, Handler: handler}
}

/*
	GetAPITaskIDSolve swagger:route GET /api/task/{id}/solve getApiTaskIdSolve

GetAPITaskIDSolve get API task ID solve API
*/
type GetAPITaskIDSolve struct {
	Context *middleware.Context
	Handler GetAPITaskIDSolveHandler
}

func (o *GetAPITaskIDSolve) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetAPITaskIDSolveParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
