// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetAPITaskIDHandlerFunc turns a function with the right signature into a get API task ID handler
type GetAPITaskIDHandlerFunc func(GetAPITaskIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAPITaskIDHandlerFunc) Handle(params GetAPITaskIDParams) middleware.Responder {
	return fn(params)
}

// GetAPITaskIDHandler interface for that can handle valid get API task ID params
type GetAPITaskIDHandler interface {
	Handle(GetAPITaskIDParams) middleware.Responder
}

// NewGetAPITaskID creates a new http.Handler for the get API task ID operation
func NewGetAPITaskID(ctx *middleware.Context, handler GetAPITaskIDHandler) *GetAPITaskID {
	return &GetAPITaskID{Context: ctx, Handler: handler}
}

/*
	GetAPITaskID swagger:route GET /api/task/{id} getApiTaskId

GetAPITaskID get API task ID API
*/
type GetAPITaskID struct {
	Context *middleware.Context
	Handler GetAPITaskIDHandler
}

func (o *GetAPITaskID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetAPITaskIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
