// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"quizzer/api/models"
)

// GetAPITaskIDOKCode is the HTTP code returned for type GetAPITaskIDOK
const GetAPITaskIDOKCode int = 200

/*
GetAPITaskIDOK Task to be worked on

swagger:response getApiTaskIdOK
*/
type GetAPITaskIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Task `json:"body,omitempty"`
}

// NewGetAPITaskIDOK creates GetAPITaskIDOK with default headers values
func NewGetAPITaskIDOK() *GetAPITaskIDOK {

	return &GetAPITaskIDOK{}
}

// WithPayload adds the payload to the get Api task Id o k response
func (o *GetAPITaskIDOK) WithPayload(payload *models.Task) *GetAPITaskIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get Api task Id o k response
func (o *GetAPITaskIDOK) SetPayload(payload *models.Task) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAPITaskIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
