name: Test

on:
    push:
        branches:
            - master

jobs:
    FormatCheck:
        strategy:
            matrix:
                go-version:
                  - latest
        runs-on: ubuntu-latest
        steps:
          - name: Install Go
            uses: actions/setup-go@v5
            with:
                go-version: ${{matrix.go-version}}
          - name: Checkout
            uses: actions/checkout@v3
            with:
                fetch-depth: 1
          - name: FormatCheck
            run: if [ `go fmt ./... | wc -l` -gt 0 ] ; then echo "Found unformatted code" ; exit 1 ; else exit 0 ; fi

    StaticCheck:
        strategy:
            matrix:
                go-version:
                  - latest
        runs-on: ubuntu-latest
        steps:
          - name: Install Go
            uses: actions/setup-go@v5
            with:
                go-version: ${{matrix.go-version}}
          - name: Checkout
            uses: actions/checkout@v3
            with:
                fetch-depth: 1
          - name: StaticCheck
            uses: dominikh/staticcheck-action@v1.3.0
            with:
                version: latest
                install-go: false
                cache-key: ${{matrix.go-version}}

    VulnerabilityCheck:
        strategy:
            matrix:
                go-version:
                  - latest
        runs-on: ubuntu-latest
        steps:
          - name: Install Go
            uses: actions/setup-go@v5
            with:
                go-version: ${{matrix.go-version}}
          - name: Checkout
            uses: actions/checkout@v3
            with:
                fetch-depth: 1
          - name: VulnerabilityCheck
            uses: kmulvey/govulncheck-action@main
            # optional
            with:
                packages: '.'

    Test:
        strategy:
            matrix:
                go-version:
                  - latest
                platform:
                  #- macos-latest
                  - ubuntu-latest
                  #- windows-latest
        runs-on: ${{matrix.platform}}
        steps:
          - name: Install Go
            uses: actions/setup-go@v5
            with:
                go-version: ${{matrix.go-version}}
          - name: Checkout
            uses: actions/checkout@v3
            with:
                fetch-depth: 1
          - name: Test
            run: go test -v ./...
